#ifndef TEST_ROLLBACK_DETERMINISM_H
#define TEST_ROLLBACK_DETERMINISM_H

/* Rollback-determinism harness (docs/rollback-determinism-harness.md).
 *
 * Empirically proves (or disproves) that the GameState/EffectState
 * save/load whitelist in src/netplay/game_state.c captures every piece
 * of mutable state the simulation depends on, by differencing the
 * ENTIRE writable data/bss image between a straight-line run and a run
 * that additionally performs save -> speculative-resimulate -> load
 * rollback cycles (the exact production save_state /
 * load_state_from_event path GekkoNet drives during netplay).
 *
 * The in-game side (this module) only records: once per outer frame it
 * hashes every writable data/bss symbol (per a symbol map generated by
 * the driver from nm) and appends a row to a stream file. The Python
 * driver, tools/rollback-determinism/check_rollback_determinism.py,
 * orchestrates baseline + rollback runs, diffs the streams, symbolizes
 * divergences, filters an explicit allowlist, and produces the
 * pass/fail verdict.
 *
 * Both hooks are inert no-ops unless --rbd-capture is set. Real bodies
 * exist only in #if DEBUG builds with ENABLE_NETPLAY=ON; otherwise the
 * stubs below compile in (args.c refuses --rbd-capture on such builds).
 */

/* Called at the top of every outer frame (before game_step_0). In a
 * rollback run (--rbd-rollback-period > 0) injects the save/resim/load
 * cycle when due. */
void RollbackDeterminism_PreFrame(void);

/* Called at the bottom of every outer frame (after game_step_1). Hashes
 * the writable image and appends a row; on reaching --rbd-frames writes
 * the stream footer, prints the summary line and requests a clean exit
 * via SDLApp_Exit(). */
void RollbackDeterminism_FrameEnd(void);

#endif // TEST_ROLLBACK_DETERMINISM_H
