/**
 * @file test_cg_ranges.c
 * Unit harness for the CG-remap table invariant (doc §8.C, the range-overlap
 * guard).
 *
 * THE INVARIANT. Within one character's `CgRemapRange[]`, no row may be
 * inverted (`first > last`) and no two rows may overlap.
 *
 * WHY IT MATTERS, precisely. `remap_cg_number` (arcade_char_data.c) walks the
 * rows and takes the FIRST match, then stops. An overlap therefore does not
 * fail, and does not warn: it applies whichever of the two deltas happens to
 * sit earlier in the array. Three consequences, in increasing order of how
 * hard they are to diagnose:
 *
 *   1. A wrong sprite, for every cell carrying a raw in the overlap.
 *   2. Row ORDER becomes part of the shipped mapping. The tables are
 *      hand-authored and deliberately unsorted (`remy_cg_ranges` opens on
 *      0x7141, then 0x0601), so there is no ordering convention to notice a
 *      violation of.
 *   3. Because ArcadeCharData_ComputeDigest() hashes the adapted spans, and
 *      that digest is the MIST netplay compatibility token, two builds whose
 *      source differs ONLY in the order of two overlapping rows would refuse
 *      to pair -- MIST_REJECT_BALANCE_MISMATCH, with nothing anywhere saying
 *      why.
 *
 * WHY THIS HARNESS EXISTS RATHER THAN THE TWO CHECKS THAT ALREADY DID.
 *
 *   - `ArcadeCharData_Init`'s SDL_assert is `#if defined(DEBUG)`. DEBUG is set
 *     only for CMAKE_BUILD_TYPE=Debug, every shipping pipeline configures
 *     Release, and THREESX_STATCHECK is a hard configure error with Debug
 *     (CMakeLists.txt) -- so no shipped and no gated binary has ever executed
 *     it.
 *   - `tools/arcade-audit/cg_audit.py`'s `check_range_overlaps()` does run it
 *     for real, and is fatal, but it is a hand-invoked ~24 s job whose module
 *     import reads `rom.bin` (gitignored, regenerated by decrypt.py) and a
 *     642 MB SF33RD.AFS. A change that only adds a row to these tables can
 *     plausibly never meet it.
 *
 * This harness is discovered by tools/gates/run-gates.sh from args.c (an
 * OPT_BOOLEAN whose help says it runs "and exit"), so it runs on every gate
 * pass without anybody adding it to a list. It checks by LOOPING the tables,
 * so a new row is covered by code that already exists.
 *
 * WHAT IT CANNOT PROVE. That any row's delta is the RIGHT delta. That is a
 * question about the ROM and the PS2 data, answered by cg_audit.py's
 * `manu_delta_gate` / class-(c) check, not by anything in-process. This
 * harness only proves the table is well formed enough that the delta a row
 * states is the delta `remap_cg_number` applies.
 */

#include <stdint.h>
#include <stdio.h>

#include "constants.h"

int CgRanges_Test_Tables(void);

#ifndef ENABLE_NETPLAY_TESTS

int CgRanges_Test_Tables(void) {
    fprintf(stderr,
            "[test_cg_ranges] not compiled in; rebuild with "
            "-DCMAKE_C_FLAGS=-DENABLE_NETPLAY_TESTS.\n");
    return 2;
}

#else

#include "arcade/arcade_char_data.h"

/* Deliberately a literal (house rule, see test_texcash_bounds.c): if a
 * sub-test is skipped or removed, coverage fails loudly instead of reporting
 * a smaller green run. */
#define EXPECTED_SUBTESTS 4

static int g_ran;
static int g_fail;
static int g_nosignal;

#define CHECK(cond, ...)                                                                                               \
    do {                                                                                                               \
        if (!(cond)) {                                                                                                 \
            g_fail += 1;                                                                                               \
            printf("  FAIL  %s:%d  ", __func__, __LINE__);                                                             \
            printf(__VA_ARGS__);                                                                                       \
            printf("\n");                                                                                              \
        }                                                                                                              \
    } while (0)

/* A control assertion. Failing one means the detector is dead, so a green
 * run on the live tables would mean nothing -- separate bucket, exit 2. */
#define CONTROL(cond, ...)                                                                                             \
    do {                                                                                                               \
        if (!(cond)) {                                                                                                 \
            g_nosignal += 1;                                                                                           \
            printf("  NO-SIGNAL  %s:%d  ", __func__, __LINE__);                                                        \
            printf(__VA_ARGS__);                                                                                       \
            printf("\n");                                                                                              \
        }                                                                                                              \
    } while (0)

/* ------------------------------------------------------------------------
 * SUB_A -- the twenty live tables, plus the five cg_se pair lists.
 *
 * The whole point of the harness. Runs against `cg_maps[]` as shipped, so a
 * row added to arcade_char_data.c is covered the moment it is added.
 * --------------------------------------------------------------------- */
static void sub_a_live_tables(void) {
    g_ran += 1;
    printf("SUB_A  live cg_maps[] + cg_se_maps[] tables\n");

    const int defects = ArcadeCharData_CgTableDefects();

    CHECK(defects == 0, "live tables report %d defect(s); each was logged above", defects);

    if (defects == 0) {
        printf("       0 defects across %d character tables\n", NUM_CHARS);
    }
}

/* ------------------------------------------------------------------------
 * SUB_B -- the detector detects an overlap (negative control).
 *
 * Without this, SUB_A's green could mean "the checker returns 0 for
 * everything". The synthetic table reproduces the exact hazard: a later row
 * shadowed by an earlier one, which `remap_cg_number` would resolve by
 * position.
 * --------------------------------------------------------------------- */
static void sub_b_detects_overlap(void) {
    g_ran += 1;
    printf("SUB_B  overlap is detected (negative control)\n");

    /* Row 1 is wholly inside row 0: remap_cg_number would take row 0's
       +0x20 for 0x0685 and row 1's -0x600 would be unreachable. */
    static const CgRemapRange shadowed[] = {
        { .first = 0x0680, .last = 0x0690, .delta = 0x20 },
        { .first = 0x0685, .last = 0x0685, .delta = -0x600 },
    };

    /* Partial overlap at the seam -- the off-by-one a hand-authored row
       actually produces. */
    static const CgRemapRange seam[] = {
        { .first = 0x0827, .last = 0x0834, .delta = 0x20 },
        { .first = 0x0834, .last = 0x08D7, .delta = 0x20 },
    };

    /* Identical bounds, opposite deltas. */
    static const CgRemapRange duplicate[] = {
        { .first = 0x0601, .last = 0x0601, .delta = 0x20 },
        { .first = 0x0601, .last = 0x0601, .delta = -0x1E0 },
    };

    CONTROL(ArcadeCharData_CgRangeDefects(shadowed, 2, "ctl-shadowed") == 1, "a shadowed row was not reported");
    CONTROL(ArcadeCharData_CgRangeDefects(seam, 2, "ctl-seam") == 1, "a one-value seam overlap was not reported");
    CONTROL(ArcadeCharData_CgRangeDefects(duplicate, 2, "ctl-duplicate") == 1, "a duplicated row was not reported");
}

/* ------------------------------------------------------------------------
 * SUB_C -- the detector detects an inverted row (negative control).
 *
 * `first > last` makes the row match nothing at all, so the character falls
 * through to `default_delta` for every raw the row was meant to fix -- a
 * silent no-op, which is the failure mode that looks most like success.
 * --------------------------------------------------------------------- */
static void sub_c_detects_inversion(void) {
    g_ran += 1;
    printf("SUB_C  inverted row is detected (negative control)\n");

    static const CgRemapRange inverted[] = {
        { .first = 0x08D7, .last = 0x08D6, .delta = 0x20 },
    };

    CONTROL(ArcadeCharData_CgRangeDefects(inverted, 1, "ctl-inverted") == 1, "an inverted row was not reported");
}

/* ------------------------------------------------------------------------
 * SUB_D -- adjacent-but-disjoint rows are CLEAN (false-positive control).
 *
 * This is the shape the table actually has after the §8.N / §33.9 / §33.9.2
 * rows landed: 0x0678 then 0x0679..0x067A then 0x067C..0x067D, and
 * 0x0683..0x0684 then 0x0685 then 0x0690..0x0692. Rows that touch at
 * `last + 1 == first` are correct, and a checker that flagged them would make
 * the discrete-rows shape §8.N requires impossible to express.
 * --------------------------------------------------------------------- */
static void sub_d_adjacency_is_clean(void) {
    g_ran += 1;
    printf("SUB_D  adjacent disjoint rows are clean (false-positive control)\n");

    static const CgRemapRange adjacent[] = {
        { .first = 0x0678, .last = 0x0678, .delta = 0x20 },
        { .first = 0x0679, .last = 0x067A, .delta = 0x20 },
        { .first = 0x067C, .last = 0x067D, .delta = 0x20 },
        { .first = 0x0683, .last = 0x0684, .delta = 0x20 },
        { .first = 0x0685, .last = 0x0685, .delta = 0x20 },
        { .first = 0x0690, .last = 0x0692, .delta = 0x20 },
    };

    /* Single-value rows are legal too -- `first == last` is not an
       inversion, and four of remy_cg_ranges' rows are exactly that. */
    CHECK(ArcadeCharData_CgRangeDefects(adjacent, 6, "ctl-adjacent") == 0,
          "adjacent disjoint rows were reported as defects");
}

/* ------------------------------------------------------------------------
 * Runner
 * --------------------------------------------------------------------- */
int CgRanges_Test_Tables(void) {
    printf("=== CG remap table invariant harness (doc §8.C) ===\n");

    sub_a_live_tables();
    printf("       (SUB_B and SUB_C feed the detector DELIBERATELY BROKEN tables; the\n"
           "        ERROR lines they print are the control firing, not a finding)\n");
    sub_b_detects_overlap();
    sub_c_detects_inversion();
    sub_d_adjacency_is_clean();

    if (g_ran != EXPECTED_SUBTESTS) {
        printf("COVERAGE FAIL: ran %d sub-test(s), expected exactly %d\n", g_ran, EXPECTED_SUBTESTS);
        return 2;
    }

    if (g_nosignal != 0) {
        printf("RESULT: NO-SIGNAL (%d control assertion(s) failed)\n", g_nosignal);
        printf("The detector did not report a table it must report, so SUB_A's result means nothing.\n");
        return 2;
    }

    if (g_fail != 0) {
        printf("RESULT: FAIL (%d assertion(s))\n", g_fail);
        return 1;
    }

    printf("RESULT: PASS (%d sub-tests)\n", g_ran);
    return 0;
}

#endif /* ENABLE_NETPLAY_TESTS */
