#ifndef KEYMAP_H
#define KEYMAP_H

#include <SDL3/SDL.h>

#define KEYMAP_CODES_PER_BUTTON 4
#define KEYMAP_BUTTON_COUNT 16

typedef enum KeymapButton {
    KEYMAP_BUTTON_UP,
    KEYMAP_BUTTON_DOWN,
    KEYMAP_BUTTON_LEFT,
    KEYMAP_BUTTON_RIGHT,
    KEYMAP_BUTTON_NORTH,
    KEYMAP_BUTTON_WEST,
    KEYMAP_BUTTON_SOUTH,
    KEYMAP_BUTTON_EAST,
    KEYMAP_BUTTON_LEFT_SHOULDER,
    KEYMAP_BUTTON_RIGHT_SHOULDER,
    KEYMAP_BUTTON_LEFT_TRIGGER,
    KEYMAP_BUTTON_RIGHT_TRIGGER,
    KEYMAP_BUTTON_LEFT_STICK,
    KEYMAP_BUTTON_RIGHT_STICK,
    KEYMAP_BUTTON_BACK,
    KEYMAP_BUTTON_START,
} KeymapButton;

void Keymap_Init();
const SDL_Scancode* Keymap_GetScancodes(KeymapButton button);

#endif
