/* GENERATED FILE — do not edit by hand.
 *
 * Regenerate with tools/netplay/gen_plw_canon_fields.py --write, which
 * derives this list from clang's record layout for PLW on both armv7 and
 * the host 64-bit target and requires the two to agree.
 *
 * PLW_CANON_FIELD_LIST is every non-pointer member of PLW in declaration
 * order; PLW_CANON_POINTER_LIST is every pointer member. Pointers are
 * excluded from the checksum because their VALUES are meaningless across
 * peers (ASLR) and their WIDTHS differ across architectures; they are
 * listed so the coverage proof can account for every byte of the struct.
 *
 * At generation time: sizeof(PLW) = 1092 (armv7), 1304 (64-bit);
 * 399 non-pointer members, 38 pointer members.
 */

#ifndef PLW_CANON_FIELDS_H
#define PLW_CANON_FIELDS_H

#define PLW_CANON_FIELD_LIST(X) \
    X(wu.be_flag) \
    X(wu.disp_flag) \
    X(wu.blink_timing) \
    X(wu.wu_operator) \
    X(wu.type) \
    X(wu.charset_id) \
    X(wu.work_id) \
    X(wu.id) \
    X(wu.rl_flag) \
    X(wu.rl_waza) \
    X(wu.before) \
    X(wu.myself) \
    X(wu.behind) \
    X(wu.listix) \
    X(wu.dead_f) \
    X(wu.timing) \
    X(wu.routine_no) \
    X(wu.old_rno) \
    X(wu.hit_stop) \
    X(wu.hit_quake) \
    X(wu.cgromtype) \
    X(wu.kage_flag) \
    X(wu.kage_hx) \
    X(wu.kage_hy) \
    X(wu.kage_prio) \
    X(wu.kage_width) \
    X(wu.kage_char) \
    X(wu.position_x) \
    X(wu.position_y) \
    X(wu.position_z) \
    X(wu.next_x) \
    X(wu.next_y) \
    X(wu.next_z) \
    X(wu.scr_mv_x) \
    X(wu.scr_mv_y) \
    X(wu.xyz) \
    X(wu.old_pos) \
    X(wu.sync_suzi) \
    X(wu.mvxy.a) \
    X(wu.mvxy.d) \
    X(wu.mvxy.kop) \
    X(wu.mvxy.index) \
    X(wu.direction) \
    X(wu.dir_old) \
    X(wu.dir_step) \
    X(wu.dir_timer) \
    X(wu.vitality) \
    X(wu.vital_new) \
    X(wu.vital_old) \
    X(wu.dm_vital) \
    X(wu.dmcal_m) \
    X(wu.dmcal_d) \
    X(wu.weight_level) \
    X(wu.cmoa.code) \
    X(wu.cmoa.koc) \
    X(wu.cmoa.ix) \
    X(wu.cmoa.pat) \
    X(wu.cmsw.code) \
    X(wu.cmsw.koc) \
    X(wu.cmsw.ix) \
    X(wu.cmsw.pat) \
    X(wu.cmlp.code) \
    X(wu.cmlp.koc) \
    X(wu.cmlp.ix) \
    X(wu.cmlp.pat) \
    X(wu.cml2.code) \
    X(wu.cml2.koc) \
    X(wu.cml2.ix) \
    X(wu.cml2.pat) \
    X(wu.cmja.code) \
    X(wu.cmja.koc) \
    X(wu.cmja.ix) \
    X(wu.cmja.pat) \
    X(wu.cmj2.code) \
    X(wu.cmj2.koc) \
    X(wu.cmj2.ix) \
    X(wu.cmj2.pat) \
    X(wu.cmj3.code) \
    X(wu.cmj3.koc) \
    X(wu.cmj3.ix) \
    X(wu.cmj3.pat) \
    X(wu.cmj4.code) \
    X(wu.cmj4.koc) \
    X(wu.cmj4.ix) \
    X(wu.cmj4.pat) \
    X(wu.cmj5.code) \
    X(wu.cmj5.koc) \
    X(wu.cmj5.ix) \
    X(wu.cmj5.pat) \
    X(wu.cmj6.code) \
    X(wu.cmj6.koc) \
    X(wu.cmj6.ix) \
    X(wu.cmj6.pat) \
    X(wu.cmj7.code) \
    X(wu.cmj7.koc) \
    X(wu.cmj7.ix) \
    X(wu.cmj7.pat) \
    X(wu.cmms.code) \
    X(wu.cmms.koc) \
    X(wu.cmms.ix) \
    X(wu.cmms.pat) \
    X(wu.cmmd.code) \
    X(wu.cmmd.koc) \
    X(wu.cmmd.ix) \
    X(wu.cmmd.pat) \
    X(wu.cmyd.code) \
    X(wu.cmyd.koc) \
    X(wu.cmyd.ix) \
    X(wu.cmyd.pat) \
    X(wu.cmcf.code) \
    X(wu.cmcf.koc) \
    X(wu.cmcf.ix) \
    X(wu.cmcf.pat) \
    X(wu.cmcr.code) \
    X(wu.cmcr.koc) \
    X(wu.cmcr.ix) \
    X(wu.cmcr.pat) \
    X(wu.cmbk.code) \
    X(wu.cmbk.koc) \
    X(wu.cmbk.ix) \
    X(wu.cmbk.pat) \
    X(wu.cmb2.code) \
    X(wu.cmb2.koc) \
    X(wu.cmb2.ix) \
    X(wu.cmb2.pat) \
    X(wu.cmb3.code) \
    X(wu.cmb3.koc) \
    X(wu.cmb3.ix) \
    X(wu.cmb3.pat) \
    X(wu.cmhs.code) \
    X(wu.cmhs.koc) \
    X(wu.cmhs.ix) \
    X(wu.cmhs.pat) \
    X(wu.cmr0.code) \
    X(wu.cmr0.koc) \
    X(wu.cmr0.ix) \
    X(wu.cmr0.pat) \
    X(wu.cmr1.code) \
    X(wu.cmr1.koc) \
    X(wu.cmr1.ix) \
    X(wu.cmr1.pat) \
    X(wu.cmr2.code) \
    X(wu.cmr2.koc) \
    X(wu.cmr2.ix) \
    X(wu.cmr2.pat) \
    X(wu.cmr3.code) \
    X(wu.cmr3.koc) \
    X(wu.cmr3.ix) \
    X(wu.cmr3.pat) \
    X(wu.cmwk) \
    X(wu.cg_olc.olc_ix) \
    X(wu.cg_ix) \
    X(wu.now_koc) \
    X(wu.char_index) \
    X(wu.current_colcd) \
    X(wu.cgd_type) \
    X(wu.pat_status) \
    X(wu.kind_of_waza) \
    X(wu.hit_range) \
    X(wu.total_paring) \
    X(wu.total_att_set) \
    X(wu.sp_tech_id) \
    X(wu.cg_type) \
    X(wu.cg_ctr) \
    X(wu.cg_se) \
    X(wu.cg_olc_ix) \
    X(wu.cg_number) \
    X(wu.cg_hit_ix) \
    X(wu.cg_att_ix) \
    X(wu.cg_extdat) \
    X(wu.cg_cancel) \
    X(wu.cg_effect) \
    X(wu.cg_eftype) \
    X(wu.cg_zoom) \
    X(wu.cg_rival) \
    X(wu.cg_add_xy) \
    X(wu.cg_next_ix) \
    X(wu.cg_status) \
    X(wu.cg_wca_ix) \
    X(wu.cg_jphos) \
    X(wu.cg_meoshi) \
    X(wu.cg_prio) \
    X(wu.cg_flip) \
    X(wu.old_cgnum) \
    X(wu.floor) \
    X(wu.ccoff) \
    X(wu.colcd) \
    X(wu.my_col_mode) \
    X(wu.my_col_code) \
    X(wu.my_priority) \
    X(wu.my_family) \
    X(wu.my_ext_pri) \
    X(wu.my_bright_type) \
    X(wu.my_bright_level) \
    X(wu.my_clear_level) \
    X(wu.my_mts) \
    X(wu.my_mr_flag) \
    X(wu.my_mr.size.x) \
    X(wu.my_mr.size.y) \
    X(wu.my_trans_mode) \
    X(wu.waku_work_index) \
    X(wu.olc_work_ix) \
    X(wu.cg_ja.boix) \
    X(wu.cg_ja.bhix) \
    X(wu.cg_ja.haix) \
    X(wu.cg_ja.mf) \
    X(wu.cg_ja.caix) \
    X(wu.cg_ja.cuix) \
    X(wu.cg_ja.atix) \
    X(wu.cg_ja.hoix) \
    X(wu.att.reaction) \
    X(wu.att.level) \
    X(wu.att.mkh_ix) \
    X(wu.att.but_ix) \
    X(wu.att.dipsw) \
    X(wu.att.guard) \
    X(wu.att.dir) \
    X(wu.att.free) \
    X(wu.att.pow) \
    X(wu.att.impact) \
    X(wu.att.piyo) \
    X(wu.att.ng_type) \
    X(wu.att.hs_me) \
    X(wu.att.hs_you) \
    X(wu.att.hit_mark) \
    X(wu.att.dmg_mark) \
    X(wu.zu_flag) \
    X(wu.at_attribute) \
    X(wu.kezuri_pow) \
    X(wu.add_arts_point) \
    X(wu.buttobi_type) \
    X(wu.att_zuru) \
    X(wu.at_ten_ix) \
    X(wu.dir_atthit) \
    X(wu.vs_id) \
    X(wu.att_hit_ok) \
    X(wu.meoshi_hit_flag) \
    X(wu.at_koa) \
    X(wu.paring_attack_flag) \
    X(wu.no_death_attack) \
    X(wu.jump_att_flag) \
    X(wu.shell_vs_refrect) \
    X(wu.renew_attack) \
    X(wu.attack_num) \
    X(wu.uketa_att) \
    X(wu.hf) \
    X(wu.hit_mark_x) \
    X(wu.hit_mark_y) \
    X(wu.hit_mark_z) \
    X(wu.kohm) \
    X(wu.dm_fushin) \
    X(wu.dm_weight) \
    X(wu.dm_butt_type) \
    X(wu.dm_zuru) \
    X(wu.dm_attribute) \
    X(wu.dm_guard_success) \
    X(wu.dm_plnum) \
    X(wu.dm_attlv) \
    X(wu.dm_dir) \
    X(wu.dm_rl) \
    X(wu.dm_impact) \
    X(wu.dm_stop) \
    X(wu.dm_quake) \
    X(wu.dm_piyo) \
    X(wu.dm_ten_ix) \
    X(wu.dm_koa) \
    X(wu.dm_work_id) \
    X(wu.dm_arts_point) \
    X(wu.dm_jump_att_flag) \
    X(wu.dm_free) \
    X(wu.dm_count_up) \
    X(wu.dm_nodeathattack) \
    X(wu.dm_exdm_ix) \
    X(wu.dm_dip) \
    X(wu.dm_kind_of_waza) \
    X(wu.attpow) \
    X(wu.defpow) \
    X(wu.shell_ix) \
    X(wu.hm_dm_side) \
    X(wu.extra_col) \
    X(wu.extra_col_2) \
    X(wu.original_vitality) \
    X(wu.hit_work_id) \
    X(wu.dmg_work_id) \
    X(wu.K5_init_flag) \
    X(wu.K5_exec_ok) \
    X(wu.kow) \
    X(wu.swallow_no_effect) \
    X(wu.E3_work_index) \
    X(wu.E4_work_index) \
    X(wu.kezurare_flag) \
    X(wu.wrd_free) \
    X(spmv_ng_flag) \
    X(spmv_ng_flag2) \
    X(player_number) \
    X(zuru_timer) \
    X(zuru_ix_counter) \
    X(zuru_flag) \
    X(tsukamarenai_flag) \
    X(kizetsu_kow) \
    X(micchaku_flag) \
    X(hos_fi_flag) \
    X(hos_em_flag) \
    X(tsukami_num) \
    X(tsukami_f) \
    X(tsukamare_f) \
    X(kind_of_catch) \
    X(old_gdflag) \
    X(guard_flag) \
    X(guard_chuu) \
    X(dm_ix) \
    X(hosei_amari) \
    X(dm_hos_flag) \
    X(dm_point) \
    X(muriyari_ugoku) \
    X(scr_pos_set_flag) \
    X(hoshi_flag) \
    X(the_same_players) \
    X(running_f) \
    X(cancel_timer) \
    X(jpdir) \
    X(jptim) \
    X(current_attack) \
    X(wkey_flag) \
    X(dead_flag) \
    X(ukemi_ok_timer) \
    X(backup_ok_timer) \
    X(uot_cd_ok_flag) \
    X(ukemi_success) \
    X(old_pos_data) \
    X(move_distance) \
    X(move_power) \
    X(sa_stop_sai) \
    X(saishin_lvdir) \
    X(sa_stop_lvdir) \
    X(sa_stop_flag) \
    X(kezurijini_flag) \
    X(image_setup_flag) \
    X(image_data_index) \
    X(caution_flag) \
    X(tc_1st_flag) \
    X(bullet_hcnt) \
    X(bhcnt_timer) \
    X(cat_break_ok_timer) \
    X(cat_break_reserve) \
    X(hazusenai_flag) \
    X(hurimukenai_flag) \
    X(tk_success) \
    X(resurrection_resv) \
    X(tk_dageki) \
    X(tk_nage) \
    X(tk_kizetsu) \
    X(tk_konjyou) \
    X(utk_dageki) \
    X(utk_nage) \
    X(utk_kizetsu) \
    X(atemi_flag) \
    X(atemi_point) \
    X(dm_vital_backup) \
    X(dm_refrect) \
    X(dm_vital_use) \
    X(exdm_ix) \
    X(meoshi_jump_flag) \
    X(cmd_request) \
    X(rl_save) \
    X(zettai_muteki_flag) \
    X(do_not_move) \
    X(just_sa_stop_timer) \
    X(total_att_hit_ok) \
    X(sa_healing) \
    X(auto_guard) \
    X(hsjp_ok) \
    X(high_jump_flag) \
    X(att_plus) \
    X(def_plus) \
    X(bs2_on_car) \
    X(bs2_area_car) \
    X(bs2_over_car) \
    X(bs2_area_car2) \
    X(bs2_over_car2) \
    X(micchaku_wall_time) \
    X(extra_jump) \
    X(air_jump_ok_time) \
    X(waku_ram_index) \
    X(permited_koa) \
    X(ja_nmj_rno) \
    X(ja_nmj_cnt) \
    X(kind_of_blocking) \
    X(metamorphose) \
    X(metamor_index) \
    X(metamor_over) \
    X(gill_ccch_go) \
    X(renew_attchar) \
    X(omop_vital_timer) \
    X(sfwing_pos) \
    X(init_E3_flag) \
    X(init_E4_flag) \
    X(pl09_dat_index) \
    X(reserv_add_y)

#define PLW_CANON_POINTER_LIST(X) \
    X(wu.target_adrs) \
    X(wu.hit_adrs) \
    X(wu.dmg_adrs) \
    X(wu.suzi_offset) \
    X(wu.char_table) \
    X(wu.se_random_table) \
    X(wu.step_xy_table) \
    X(wu.move_xy_table) \
    X(wu.overlap_char_tbl) \
    X(wu.olc_ix_table) \
    X(wu.rival_catch_tbl) \
    X(wu.curr_rca) \
    X(wu.set_char_ad) \
    X(wu.hit_ix_table) \
    X(wu.body_adrs) \
    X(wu.h_bod) \
    X(wu.hand_adrs) \
    X(wu.h_han) \
    X(wu.dumm_adrs) \
    X(wu.h_dumm) \
    X(wu.catch_adrs) \
    X(wu.h_cat) \
    X(wu.caught_adrs) \
    X(wu.h_cau) \
    X(wu.attack_adrs) \
    X(wu.h_att) \
    X(wu.h_eat) \
    X(wu.hosei_adrs) \
    X(wu.h_hos) \
    X(wu.att_ix_table) \
    X(wu.my_effadrs) \
    X(cp) \
    X(dm_step_tbl) \
    X(as) \
    X(sa) \
    X(cb) \
    X(py) \
    X(rp)

#endif // PLW_CANON_FIELDS_H
