set(IMGUI_SOURCES
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_draw.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_tables.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_widgets.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_demo.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_impl_sdl3.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/imgui/imgui_impl_sdlrenderer3.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/dcimgui/dcimgui.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/dcimgui/dcimgui_impl_sdl3.cpp
    ${PROJECT_SOURCE_DIR}/src/imgui/dcimgui/dcimgui_impl_sdlrenderer3.cpp
)
